
- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started

- name: Create databases
  sudo: yes
  sudo_user: postgres
  postgresql_db:
    name: "{{item.database}}"
    encoding: "{{postgresql_encoding}}"
    lc_collate: "{{postgresql_locale}}"
    lc_ctype: "{{postgresql_locale}}"
    template: "{{item.template | default('template0')}}"
    state: present
  with_items: postgresql_databases
  when: postgresql_databases | length > 0
