# This is the main task, which simply includes all necessary sub tasks.
---
- include: install.yml
  tags: [postgresql, postgresql-install]

- include: configure.yml
  tags: [postgresql, postgresql-configure]

- include: extensions.yml
  tags: [postgresql, postgresql-extensions]

- include: databases.yml
  tags: [postgresql, postgresql-databases]

- include: users.yml
  tags: [postgresql, postgresql-users]
